# 项目默认的配置

server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000 # 最大线程数，缺省：200
    max-connections: 20000 # 最大连接数
    min-spare-threads: 30 # 初始化线程数，缺省：25

spring:
  profiles:
    active: dev, config
  application:
    name: mq-web
  # 资源信息
  messages:
    basename: i18n/messages # 国际化资源文件路径
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # 文件上传
  servlet:
    multipart:
      max-file-size:  20MB
      max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      enabled: true # 热部署开关
  #  开启动态代理
  aop:
    proxy-target-class: true

# actuator的所有端口暴露出
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    # 启用shutdown端点,用来实现服务优雅的停机
    shutdown:
      enabled: true

# PageHelper分页插件配置
pagehelper:
  helperDialect: mysql

# 每页最多显示记录个数
page:
  maxsize: 10
